---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: appa
spec:
  owner: infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: worker-app1
spec:
  type: backend
  lifecycle: production
  owner: infrastructure
  system: appa
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-appa
  description: retornar informações pedidos
spec:
  type: pedidos
  lifecycle: production
  owner: infrastructure
  system: appa
  definition: |
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: queue-artist
  description: pass artist details
spec:
  type: rabbit
  owner: infrastructure
  system: appa
